services:
  app:
    image: mfeliciano1/servlets-app:prod
    container_name: servlets_app
    restart: unless-stopped
    ports:
      - "8080:8080"

    environment:
      DB_HOST: ${AWS_RDS_HOST}
      DB_PORT: ${AWS_RDS_PORT}
      POSTGRES_DB: ${AWS_RDS_DB}
      POSTGRES_USER: ${AWS_RDS_USER}

      ACTIVEMQ_BROKER_URL: ${AWS_ACTIVEMQ_BROKER_URL}

      STORAGE_PROVIDER: s3

      CLOUDFRONT_PRIVATE_KEY_PATH: /run/secrets/cloudfront_pk

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}

      JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseG1GC -XX:+UseStringDeduplication"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/v1/health/up" ]
      interval: 30s
      timeout: 10s
      retries: 5

    volumes:
      - /run/secrets:/run/secrets:ro

networks:
  default:
    driver: bridge