# Make sure to create a secrets file or use environment variables to store sensitive information:
#
#      POSTGRES_PASSWORD:
#      POSTGRES_USER:
#      ARTEMIS_USER:
#      ARTEMIS_PASSWORD:
#      SECURITY_JWT_KEY:
#      PROVIDER_ACCESS_KEY:
#      PROVIDER_SECRET_KEY:

services:
  app:
    image: mfeliciano1/servlets-app:ec2
    container_name: servlets_app
    restart: unless-stopped
    ports:
      - "8080:8080"

    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_DB: ${EC2_DB}

      ACTIVEMQ_BROKER_URL: tcp://activemq:61616?reconnectAttempts=-1&failoverAttempts=-1&retryInterval=2000&retryIntervalMultiplier=1.5&maxRetryInterval=60000

      STORAGE_PROVIDER: s3

      CLOUDFRONT_PRIVATE_KEY_PATH: /run/secrets/cloudfront_pk

      JAVA_OPTS: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:+UseStringDeduplication"

    volumes:
      - ./secrets/cloudfront-private-pkcs8.pem:/run/secrets/cloudfront_pk:ro

    depends_on:
      db:
        condition: service_healthy
      activemq:
        condition: service_healthy

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/v1/health/up" ]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:15-alpine
    container_name: ec2_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${EC2_DB}

    volumes:
      - /data/postgres:/var/lib/postgresql/data
      - ./secrets/postgres:/run/secrets:ro

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${EC2_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 12

  activemq:
    image: apache/activemq-artemis:2.44.0
    container_name: ec2_activemq
    restart: unless-stopped
    ports:
      - "61616:61616"
      - "8161:8161"

    volumes:
      - /data/broker:/var/lib/artemis/data
      - ./secrets/activemq:/var/lib/artemis/etc:ro

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8161" ]
      interval: 10s
      timeout: 5s
      retries: 12

networks:
  default:
    driver: bridge