# Docker Compose configuration for the application, PostgreSQL database, and ActiveMQ Artemis message broker.

# Local: To run with a local profile:
# docker compose -f docker-compose.dev.yml --env-file .env.dev up -d --build

services:
  app:
    build:
      context: .
    container_name: servlets_app_local
    restart: unless-stopped
    env_file:
      - ./.env.dev
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      # ActiveMQ interno
      ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      ARTEMIS_USER: ${LOCAL_ARTEMIS_USER}
      ARTEMIS_PASSWORD: ${LOCAL_ARTEMIS_PASSWORD}
      POSTGRES_DB: ${LOCAL_DB_NAME}
      POSTGRES_USER: ${LOCAL_DB_USER}
      POSTGRES_PASSWORD: ${LOCAL_DB_PASSWORD}
      JAVA_OPTS: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -Dapp.config.file=app-dev.yml"
      # Opcional: modo local
      APP_MODE: local
    depends_on:
      db:
        condition: service_healthy
      activemq:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/v1/health/up" ]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:15-alpine
    container_name: dev_postgres
    restart: unless-stopped
    env_file:
      - ./.env.dev
    environment:
      POSTGRES_USER: ${LOCAL_DB_USER}
      POSTGRES_PASSWORD: ${LOCAL_DB_PASSWORD}
      POSTGRES_DB: ${LOCAL_DB_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${LOCAL_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 12

  activemq:
    image: apache/activemq-artemis:2.44.0
    container_name: dev_activemq
    restart: unless-stopped
    env_file:
      - ./.env.dev
    environment:
      ARTEMIS_USER: ${LOCAL_ARTEMIS_USER}
      ARTEMIS_PASSWORD: ${LOCAL_ARTEMIS_PASSWORD}
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - ./data/broker:/var/lib/artemis/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8161" ]
      interval: 5s
      timeout: 5s
      retries: 12

networks:
  default:
    driver: bridge

# Comandos Docker individuais para referÃªncia:
# docker run -d --name servlets-postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=uma_senha_segura -e POSTGRES_DB=servletsdb -p 5432:5432 --restart unless-stopped postgres:15
#docker run -d --name dev_activemq -e ARTEMIS_USER=artemis -e ARTEMIS_PASSWORD=artemis -p 61616:61616 -p 8161:8161 --restart unless-stopped apache/activemq-artemis:2.44.0