apiVersion: v1
kind: ConfigMap
metadata:
  name: servlets-config
data:
#  DOMAIN: "app.seudominio.com"
  EMAIL: "your_email"
  #  Database Configuration
  DB_HOST: "postgres"
  DB_PORT: "5432"
  POSTGRES_DB: "servletsdb"
  POSTGRES_USER: "postgres"
  #  ActiveMQ Configuration
  ACTIVEMQ_BROKER_URL: "tcp://activemq:61616"
  ARTEMIS_USER: "artemis"
  # SMTP Configuration
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "your_email"
