apiVersion: v1
kind: Secret
metadata:
  name: servlets-secret
type: Opaque
data:
  POSTGRES_PASSWORD: "your_base64_encoded_postgres_password_here"
  SECURITY_JWT_KEY: "your_long_base64_encoded_jwt_key_here"
  ARTEMIS_PASSWORD: "your_base64_encoded_artemis_password_here"
  SMTP_PASS: "your_base64_encoded_smtp_password_here"
  PROVIDER_ACCESS_KEY: "your_base64_encoded_provider_access_key_here"
  PROVIDER_SECRET_KEY: "your_base64_encoded_provider_secret_key_here"
