apiVersion: apps/v1
kind: Deployment
metadata:
  name: servlets-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servlets-app
  template:
    metadata:
      labels:
        app: servlets-app
    spec:
      containers:
        - name: servlets-app
          image: mfeliciano1/servlets-app:dev
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres

            - name: MQ_HOST
              value: activemq

            - name: CLOUDFRONT_PK_PATH
              value: /run/secrets/cloudfront/cloudfront_pk

          envFrom:
            - configMapRef:
                name: servlets-config
            - secretRef:
                name: servlets-secret

          volumeMounts:
            - name: cloudfront-key
              mountPath: /run/secrets/cloudfront
              readOnly: true

      volumes:
        - name: cloudfront-key
          secret:
            secretName: cloudfront-private-key