services:
  app:
    image: mfeliciano1/servlets-app:prod
    container_name: servlets_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    mem_limit: 1g

    environment:
      DB_HOST: ${AWS_RDS_HOST}
      DB_PORT: ${AWS_RDS_PORT}
      DB: ${AWS_RDS_DB}
      DB_USER: ${AWS_RDS_USER}

      BROKER_URL: ${AWS_BROKER_URL}

      CLOUDFRONT_PK_PATH: /run/secrets/cloudfront_pk

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}

      JAVA_OPTS: "-Xms320m -Xm640m -XX:MaxMetaspaceSize=192m -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MaxGCPauseMillis=200"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/v1/health/up" ]
      interval: 30s
      timeout: 10s
      retries: 5

    volumes:
      - /run/secrets:/run/secrets:ro

networks:
  default:
    driver: bridge